epochs: 20
log_n_steps: 1
log_run: True
use_early_stopping: True # Based on val acc
early_stopping_patience: 5

model:
  model_name: vanilla_cnn
  n_layers: 4

optim:
  lr: 1.0e-4

data:
  name: apple
  data_dir: data/apple_dataset/datasets
  batch_size: 8
  num_workers: 4